// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaRodeio.Data;

#nullable disable

namespace SistemaRodeio.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaRodeio.Models.Animal", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("idade")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("peso")
                        .HasColumnType("real");

                    b.Property<int>("tipoAnimalid")
                        .HasColumnType("int");

                    b.Property<float>("valor")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.HasIndex("tipoAnimalid");

                    b.ToTable("Animais");
                });

            modelBuilder.Entity("SistemaRodeio.Models.Cidade", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sigla")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("id");

                    b.ToTable("Cidades");
                });

            modelBuilder.Entity("SistemaRodeio.Models.Competidor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("cidadeid")
                        .HasColumnType("int");

                    b.Property<int>("idade")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("vitorias")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("cidadeid");

                    b.ToTable("Competidores");
                });

            modelBuilder.Entity("SistemaRodeio.Models.Round", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("animalid")
                        .HasColumnType("int");

                    b.Property<int>("competidorid")
                        .HasColumnType("int");

                    b.Property<DateTime>("data")
                        .HasColumnType("datetime2");

                    b.Property<float>("notAnimal")
                        .HasColumnType("real");

                    b.Property<float>("notCompetidor")
                        .HasColumnType("real");

                    b.Property<float>("penalidade")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.HasIndex("animalid");

                    b.HasIndex("competidorid");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("SistemaRodeio.Models.TipoAnimal", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("TiposAnimais");
                });

            modelBuilder.Entity("SistemaRodeio.Models.Animal", b =>
                {
                    b.HasOne("SistemaRodeio.Models.TipoAnimal", "tipoAnimal")
                        .WithMany()
                        .HasForeignKey("tipoAnimalid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tipoAnimal");
                });

            modelBuilder.Entity("SistemaRodeio.Models.Competidor", b =>
                {
                    b.HasOne("SistemaRodeio.Models.Cidade", "cidade")
                        .WithMany()
                        .HasForeignKey("cidadeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cidade");
                });

            modelBuilder.Entity("SistemaRodeio.Models.Round", b =>
                {
                    b.HasOne("SistemaRodeio.Models.Animal", "animal")
                        .WithMany()
                        .HasForeignKey("animalid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaRodeio.Models.Competidor", "competidor")
                        .WithMany()
                        .HasForeignKey("competidorid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("animal");

                    b.Navigation("competidor");
                });
#pragma warning restore 612, 618
        }
    }
}
